[general]
import = ["~/.config/alacritty/themes/black-catppuccin.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

[window]
opacity = 1
dynamic_title = true
